from __future__ import annotations

__all__: list[str] = ["IOProcessor", "IOProcessorNumber", "MyProc", "NProcs"]

def IOProcessor() -> bool: ...
def IOProcessorNumber() -> int: ...
def MyProc() -> int: ...
def NProcs() -> int: ...
