name: intel

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-intel
  cancel-in-progress: true

jobs:
  tests-oneapi-sycl:
    name: oneAPI SYCL 3D
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dpcpp.sh
    - name: Build & Install
      # mkl/rng/device/detail/mrg32k3a_impl.hpp has a number of sign-compare error
      # mkl/rng/device/detail/mrg32k3a_impl.hpp has missing braces in array-array initalization
      env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual -Wextra-semi -Wunreachable-code -Wnon-virtual-dtor -Wno-sign-compare -Wno-missing-braces"}
      run: |
        set +e
        source /opt/intel/oneapi/setvars.sh
        set -e

        export CC=$(which icx)
        export CXX=$(which icpx)
        python3 -m pip install -U pip setuptools wheel
        python3 -m pip install -U cmake
        python3 -m pip install -U pytest mpi4py

        cmake -S . -B build               \
              -DCMAKE_BUILD_TYPE=Release  \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DBUILD_SHARED_LIBS=ON      \
              -DAMReX_GPU_BACKEND=SYCL    \
              -DAMReX_MPI=ON              \
              -DAMReX_SPACEDIM="3"
        cmake --build build --target pip_install -j 2

# "Classic" EDG Intel Compiler
# Ref.: https://github.com/rscohn2/oneapi-ci
# intel-basekit intel-hpckit are too large in size
  tests-icc:
    name: ICC
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get -qqq update
        sudo apt-get install -y wget build-essential pkg-config cmake ca-certificates gnupg
        sudo wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update
        sudo apt-get install -y intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-compiler-fortran intel-oneapi-mpi-devel
    - name: build
      env: {CXXFLAGS: "-Werror"}
      run: |
        set +e
        source /opt/intel/oneapi/setvars.sh
        set -e

        export CXX=$(which icpc)
        export CC=$(which icc)
        python3 -m pip install -U pip setuptools wheel
        python3 -m pip install -U cmake
        python3 -m pip install -U pytest mpi4py

        cmake -S . -B build               \
              -DCMAKE_BUILD_TYPE=Debug    \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DBUILD_SHARED_LIBS=ON      \
              -DAMReX_MPI=ON              \
              -DAMReX_SPACEDIM="1;2;3"
        cmake --build build --target pip_install -j 2

    - name: Run tests
      run: |
        set +e
        source /opt/intel/oneapi/setvars.sh
        set -e
        cd build
        ctest --output-on-failure
