name: windows

on: [push, pull_request]

jobs:
  msvc:
    name: MSVC w/o MPI
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build & Install
      run: |
        python3 -m pip install -U pip pytest
        python3 -m pip install -v .
        python3 -c "import amrex; print(amrex.__version__)"
    - name: Unit tests
      run: |
        python3 -m pytest tests

  # Build libamrex and all tutorials
  clang:
    if: ${{ false }}  # disable for now
    name: Clang w/o MPI
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build & Install
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\vc\Auxiliary\build\vcvarsall.bat" x64

        python3 -m pip install -U pip setuptools wheel pytest
        if errorlevel 1 exit 1

        cmake -S . -B build               ^
              -T "ClangCl"                ^
              -DCMAKE_VERBOSE_MAKEFILE=ON ^
              -DAMReX_MPI=OFF
        if errorlevel 1 exit 1

        cmake --build build --config RelWithDebInfo --target pip_install -j 2
        if errorlevel 1 exit 1

        ctest --test-dir build --config RelWithDebInfo --output-on-failure
        if errorlevel 1 exit 1
