name: 🪟 Windows

on: [workflow_call]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-windows
  cancel-in-progress: true

jobs:
  msvc:
    name: MSVC w/o MPI Static Release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Build & Install
      env:
        # Work-around for windows-latest GH runner issue, see
        # https://github.com/actions/runner-images/issues/10004
        CXXFLAGS: "/D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR"
      run: |
        set "CMAKE_BUILD_PARALLEL_LEVEL=4"

        python3 -m pip install -U pip
        python3 -m pip install -U pandas pytest
        python3 -m pip install -v .
        if(!$?) { Exit $LASTEXITCODE }

        python3 -c "import amrex.space1d as amr; print(amr.__version__)"
        python3 -c "import amrex.space2d as amr; print(amr.__version__)"
        python3 -c "import amrex.space3d as amr; print(amr.__version__)"
    - name: Unit tests
      shell: cmd
      run: python3 -m pytest tests

  clang:
    name: Clang w/o MPI Shared Debug
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build
      run: |
        python3 -m pip install -U pip setuptools wheel pytest
        python3 -m pip install -U cmake
        python3 -m pip install -r requirements.txt

        cmake -S . -B build               `
              -T "ClangCl"                `
              -DCMAKE_VERBOSE_MAKEFILE=ON `
              -DBUILD_SHARED_LIBS=ON      `
              -DAMReX_MPI=OFF             `
              -DAMReX_SPACEDIM="1;2;3"
        if(!$?) { Exit $LASTEXITCODE }

        cmake --build build --config Debug -j 4
        if(!$?) { Exit $LASTEXITCODE }
    - name: Unit tests
      run: |
        ctest --test-dir build -C Debug --output-on-failure
    - name: Install
      run: |
        cmake --build build --config Debug --target install
        if(!$?) { Exit $LASTEXITCODE }
        cmake --build build --config Debug --target pip_install
        if(!$?) { Exit $LASTEXITCODE }
    - name: Unit tests as Installed
      run: |
        $env:PATH += ';C:/Program Files (x86)/pyAMReX/bin/'
        rm -r -fo build
        python3 -m pytest tests
