name: windows

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-windows
  cancel-in-progress: true

jobs:
  msvc:
    name: MSVC w/o MPI
    runs-on: windows-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build & Install
      run: |
        python3 -m pip install -U pip pytest
        python3 -m pip install -v .
        python3 -c "import amrex; print(amrex.__version__)"
    - name: Unit tests
      shell: cmd
      run: |
        python3 -m pytest tests

  clang:
    name: Clang w/o MPI
    runs-on: windows-latest
    env: {PYAMREX_LIBDIR: build/lib/site-packages/amrex/Debug/}
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build & Install
      run: |
        python3 -m pip install -U pip setuptools wheel pytest
        python3 -m pip install -U cmake

        cmake -S . -B build               `
              -T "ClangCl"                `
              -DCMAKE_VERBOSE_MAKEFILE=ON `
              -DAMReX_MPI=OFF

        cmake --build build --config Debug -j 2
        python3 -m pip install -v .
    - name: Unit tests
      run: |
        ctest --test-dir build -C Debug --output-on-failure
