name: windows

on: [push, pull_request]

jobs:
  msvc:
    name: MSVC w/o MPI
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build & Install
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\vc\Auxiliary\build\vcvarsall.bat" x64

        python3 -m pip install -U pip pytest
        python3 -m pip install -v .
        if errorlevel 1 exit 1

        python3 -c "import amrex; print(amrex.__version__)"
        if errorlevel 1 exit 1
    - name: Unit tests
      shell: cmd
      run: |
        python3 -m pytest tests
        if errorlevel 1 exit 1

  clang:
    name: Clang w/o MPI
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build & Install
      run: |
        C:\hostedtoolcache\windows\Python\3.10.2\x64\python3.exe `
            -m pip install -U pip setuptools wheel pytest

        cmake -S . -B build               `
              -T "ClangCl"                `
              -DCMAKE_VERBOSE_MAKEFILE=ON `
              -DAMReX_MPI=OFF

        cmake --build build --config RelWithDebInfo --target pip_install -j 2

    - name: Unit tests
      run: |
        ctest --test-dir build -C RelWithDebInfo --output-on-failure
