name: 🪟 Windows

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-windows
  cancel-in-progress: true

jobs:
  msvc:
    name: MSVC w/o MPI static release
    runs-on: windows-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build & Install
      run: |
        python3 -m pip install -U pip pytest
        python3 -m pip install -v .
        if(!$?) { Exit $LASTEXITCODE }

        python3 -c "import amrex; print(amrex.__version__)"
    - name: Unit tests
      shell: cmd
      run: python3 -m pytest tests

  clang:
    name: Clang w/o MPI shared debug
    runs-on: windows-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build
      run: |
        python3 -m pip install -U pip setuptools wheel pytest
        python3 -m pip install -U cmake
        python3 -m pip install -r requirements.txt

        cmake -S . -B build               `
              -T "ClangCl"                `
              -DCMAKE_VERBOSE_MAKEFILE=ON `
              -DBUILD_SHARED_LIBS=ON      `
              -DAMReX_MPI=OFF
        if(!$?) { Exit $LASTEXITCODE }

        cmake --build build --config Debug -j 2
        if(!$?) { Exit $LASTEXITCODE }
    - name: Unit tests
      run: |
        ctest --test-dir build -C Debug --output-on-failure
    - name: Install
      run: |
        cmake --build build --config Debug --target install
        if(!$?) { Exit $LASTEXITCODE }
        cmake --build build --config Debug --target pip_install
        if(!$?) { Exit $LASTEXITCODE }
