name: 🪟 Windows

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-windows
  cancel-in-progress: true

jobs:
  msvc:
    name: MSVC w/o MPI
    runs-on: windows-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build & Install
      run: |
        python3 -m pip install -U pip pytest
        python3 -m pip install -v .
        if(!$?) { Exit $LASTEXITCODE }

        python3 -c "import amrex; print(amrex.__version__)"
    - name: Unit tests
      shell: cmd
      run: |
        python3 -m pytest tests

  clang:
    name: Clang w/o MPI
    runs-on: windows-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build & Install
      run: |
        python3 -m pip install -U pip setuptools wheel pytest
        python3 -m pip install -U cmake

        cmake -S . -B build               `
              -T "ClangCl"                `
              -DCMAKE_VERBOSE_MAKEFILE=ON `
              -DBUILD_SHARED_LIBS=ON      `
              -DAMReX_MPI=OFF
        if(!$?) { Exit $LASTEXITCODE }

        cmake --build build --config Debug -j 2
        if(!$?) { Exit $LASTEXITCODE }

        llvm-objdump -p build\lib\site-packages\amrex\amrex_pybind.cp311-win_amd64.pyd

        cmake --build build --config Debug --target install
        if(!$?) { Exit $LASTEXITCODE }
        cmake --build build --config Debug --target pip_install
        if(!$?) { Exit $LASTEXITCODE }

        llvm-objdump -p  "C:\Program Files (x86)\pyAMReX\bin\amrex.dll"

        Get-Childitem -Path C:\* -Recurse -Filter "*python311.dll, *amrex.dll, *MSVCP140D.dll, KERNEL32.dll, VCRUNTIME140D.dll, VCRUNTIME140_1D.dll, ucrtbased.dll"

    - name: Unit tests
      run: |
        $env:Path += "C:\Program Files (x86)\pyAMReX\bin"
        (Get-Command ctest).Path
        gflags /i C:\hostedtoolcache\windows\Python\3.11.1\x64\Scripts\ctest.exe +sls
        cdb -c "g;q" ctest --test-dir build -C Debug --output-on-failure
