# Copyright 2020-2021
#
# This file is part of HiPACE++.
#
# Authors: Axel Huebl, MaxThevenet, Severin Diederichs
# License: BSD-3-Clause-LBNL

name: 🗃️ Zenodo

on: [push, pull_request]

jobs:
  zenodo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Validate Zenodo Metadata
        uses: vsoch/zenodo-validator@main
        with:
          path: '.zenodo.json'
